#!/bin/bash
export TEMPO2=$PSRSOFT_USR/share/tempo2

pkg=tempo2
cd src/$pkg
./configure --prefix=$PSRSOFT_USR && make $PSRSOFT_MAKEOPTS && make install &> make.log
ex=$?
if [ $ex != 0 ] ; then
	exit $ex
fi

cat make.log
cat make.log | grep 'install -c' | sed -e "s:.*install -c .*[' ]$PSRSOFT_USR/\([^ ]*/[^']*\)'*:\\rm -f \1:g" | sort -u >> $PSRSOFT_USR/var/psrsoft/uninstallers/$pkg
echo "rm -rf src/$pkg" >> $PSRSOFT_USR/var/psrsoft/uninstallers/$pkg

